server:
  port: 15502

notification_plugin: http://sofia-notification-plugin:15555

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: NOTIFICATIONS
          uri: ${notification_plugin}
          predicates:
            - Path=/api/asset-image/**, /api/asset-image, /api/notification/**, /api/notification

logging:
  level:
    org.springframework.cloud.gateway: DEBUG